debug: false

# api server listen address
server:
  host: "0.0.0.0"
  port: "3000"

# fabric connection config
fabric:
  ccPath: "/tmp/.fabricappworkdir/connection.yaml"
  walletPath: "/tmp/.fabricappworkdir/wallet"
  orgName: "org1"

admin:
  username: "orgadmin"
  password: "passwd"

sqlite:
  dbPath: "/tmp/.fabricappworkdir/emalibctest.db"

# jwt
jwt:
  secret: "emali.io.secret"
  # hours
  # 10days = 10 * 24
  expire: 240

express:
  host: "localhost"
  port: "3001"