# when debug is true, server will log request headers
debug: false

# api server listen address
server:
  host: "0.0.0.0"
  port: "9000"

# fabric connection config
fabric:
  ccPath: "/tmp/.fabricappworkdir/connection.yaml"
  walletPath: "/tmp/.fabricappworkdir/wallet"
  orgName: "org1"

# used for jwt and ca registrar
admin:
  username: "orgadmin"
  password: "passwd"

couchdb:
  hostPort: "localhost:5984"
  user: "admin"
  passwd: "passwd"
  defaultDbName: "useraccount"

# jwt
jwt:
  secret: "emali.io.secret"
  # hours
  # 10days = 10 * 24
  expireHours: 240

