package model

import (
	"encoding/json"
)

// public state structure
// store in ledger and couchdb
type PublicState struct {
	// from user's input dataId
	Id string `json:"id"`

	// application name
	AppName string `json:"appName"`

	// creator
	CreatorMSPID string `json:"creatorMSPId"`
	CreatorId    string `json:"creatorId"`

	// business data in json format
	Data json.RawMessage `json:"data"`

	// private data meta info
	PrivateMetaInfo *PrivateMetaInfo `json:"privateMetaInfo"`

	// create/update time
	CreatedAt int64 `json:"createdAt"`
	UpdatedAt int64 `json:"updatedAt"`
}

// private data meta info
// used for retrieve
// one may share private data to many organizations
type PrivateMetaInfo struct {
	// private data id, generated by internal system
	SystemId  string            `json:"systemId"`
	CreateOrg *PrivateOrgInfo   `json:"createOrg"`
	ShareOrgs []*PrivateOrgInfo `json:"shareOrgs"`
}

type PrivateOrgInfo struct {
	// org's msp id
	MSPID string `json:"mspId"`
	// collection name
	Name string `json:"name"`
}

type PrivateState struct {
	// private data id, generate by internal system
	Id           string          `json:"id"`
	PublicDataId string          `json:"publicDataId"`
	Data         json.RawMessage `json:"data"`
	CreatedAt    int64           `json:"createdAt"`
}

// when get/query public world state, the response structure
type PublicResponse struct {
}

// when get/query private world state, the response structure
type PrivateResponse struct {
}
